packages:
  - 'packages/*'
  - 'domains/*'
  - 'web'
catalog:
  "@trpc/client": 11.5.1
  "@trpc/server": 11.5.1
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.1
  "react": 19.2.0
  "react-dom": 19.2.0
  "typescript": 5.9.3
  "vite": 7.1.9
  "zod": 4.1.11