packages:
  - 'packages/*'
  - 'domains/*'
  - 'web'
catalog:
  "@trpc/client": 11.5.1
  "@trpc/server": 11.5.1
  "@types/react": 18.3.12
  "@types/react-dom": 18.3.5
  "react": 18.3.1
  "react-dom": 18.3.1
  "zod": 4.1.11