common:
  projectName: purple-stack
  dnsRandomString: xwtce
  region: REGION # e.g. eu-central-1
  runtime: nodejs14.x
  deploymentBucket: purple-stack-deployments # your S3 bucket
  logRetentionInDays: 90
  versionFunctions: false
  apiGatewayShouldStartNameWithService: true # https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE

ci:
  prodAwsRole: arn:aws:iam::000000000000:role/ReplaceCiRole
  stagingAwsRole: arn:aws:iam::000000000000:role/ReplaceCiRole

vpc: ~
  # securityGroupIds:
  #   - SC_ID
  # subnetIds:
  #   - SUBNET_ID

monitoring:
  stages:
    - some-stage-here
  topic: arn:aws:sns:REGION:ACCOUNT_ID:TOPIC_NAME

frontend:
  domain: purple-stack.com
  certificate: arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERT_ID
