/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const DepositLazyImport = createFileRoute('/deposit')()
const WithdrawalLazyImport = createFileRoute('/withdrawal')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => rootRoute
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

const DepositLazyRoute = DepositLazyImport.update({
	id: '/deposit',
	path: '/deposit',
	getParentRoute: () => rootRoute
} as any).lazy(() => import('./routes/deposit').then((d) => d.Route))

const WithdrawalLazyRoute = WithdrawalLazyImport.update({
	id: '/withdrawal',
	path: '/withdrawal',
	getParentRoute: () => rootRoute
} as any).lazy(() => import('./routes/withdrawal').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/': {
			id: '/'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof IndexLazyImport
			parentRoute: typeof rootRoute
		}
		'/deposit': {
			id: '/deposit'
			path: '/deposit'
			fullPath: '/deposit'
			preLoaderRoute: typeof DepositLazyImport
			parentRoute: typeof rootRoute
		}
		'/withdrawal': {
			id: '/withdrawal'
			path: '/withdrawal'
			fullPath: '/withdrawal'
			preLoaderRoute: typeof WithdrawalLazyImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	'/': typeof IndexLazyRoute
	'/deposit': typeof DepositLazyRoute
	'/withdrawal': typeof WithdrawalLazyRoute
}

export interface FileRoutesByTo {
	'/': typeof IndexLazyRoute
	'/deposit': typeof DepositLazyRoute
	'/withdrawal': typeof WithdrawalLazyRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	'/': typeof IndexLazyRoute
	'/deposit': typeof DepositLazyRoute
	'/withdrawal': typeof WithdrawalLazyRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: '/' | '/deposit' | '/withdrawal'
	fileRoutesByTo: FileRoutesByTo
	to: '/' | '/deposit' | '/withdrawal'
	id: '__root__' | '/' | '/deposit' | '/withdrawal'
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	IndexLazyRoute: typeof IndexLazyRoute
	DepositLazyRoute: typeof DepositLazyRoute
	WithdrawalLazyRoute: typeof WithdrawalLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
	IndexLazyRoute: IndexLazyRoute,
	DepositLazyRoute: DepositLazyRoute,
	WithdrawalLazyRoute: WithdrawalLazyRoute
}

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */
